name: CMake

on:
  push:
    #branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  OIDN_VERSION: "1.4.0"
  VULKAN_VERSION: "1.3.216.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        version: 1.0.2
        packages: libasound2-dev xorg-dev libembree-dev cmake-curses-gui libtbb-dev
        
    - name: Cache OIDN
      id: cache-oidn
      uses: actions/cache@v3
      with:
        path: |
          ~/usr/include/OpenImageDenoise
          ~/usr/lib64/libOpenImageDenoise.so*
        key: ${{ runner.os }}-oidn-${{env.OIDN_VERSION}}
    
    #- if: ${{ steps.cache-oidn.outputs.cache-hit == 'false' }}
    - name: Install OIDN
      run: |
        mkdir -p ~/oidn
        pushd ~/oidn
        wget https://github.com/OpenImageDenoise/oidn/releases/download/v${{env.OIDN_VERSION}}/oidn-${{env.OIDN_VERSION}}.x86_64.linux.tar.gz
        tar -xv --strip-components=1 -f oidn-${{env.OIDN_VERSION}}.x86_64.linux.tar.gz
        sudo cp -R ./include /usr
        sudo cp -R ./lib/* /usr/lib64/
        rm ./oidn-${{env.OIDN_VERSION}}.x86_64.linux.tar.gz
        popd

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: $VULKAN_VERSION
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Configure + Build
      run: |
        chmod u+x build.sh
        ./build.sh
